name: Deploy to Test

on:
  push:
    branches: [ test ]
    
env:
  AZURE_FUNCTIONAPP_NAME: ups-microservices-test
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './UPSMicroservices'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
      with:
        ref: test

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Debug --output ./output
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_TEST }}
    #- name: Create Pull Request to Next Branch in Pipeline
      #id: cpr
      #uses: peter-evans/create-pull-request@v3
      #with:
        #base: test
        #branch: staging
